definitions:
  dtos.LoginDTO:
    properties:
      password:
        type: string
      username:
        type: string
    required:
    - password
    - username
    type: object
info:
  contact: {}
paths:
  /api/ads:
    get:
      consumes:
      - application/json
      description: SOUQ Ads
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      tags:
      - ads
  /api/catalog:
    get:
      consumes:
      - application/json
      description: Get catalog
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      tags:
      - catalog
  /api/login:
    post:
      consumes:
      - application/json
      description: Login to i-Ma'luum
      parameters:
      - description: User object
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/dtos.LoginDTO'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      tags:
      - login
  /api/result:
    get:
      description: Get result from i-Ma'luum
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      tags:
      - scraper
  /api/schedule:
    get:
      description: Get schedule from i-Ma'luum
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      tags:
      - scraper
    post:
      description: Login and get schedule from i-Ma'luum
      parameters:
      - description: User object
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/dtos.LoginDTO'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      tags:
      - scraper
swagger: "2.0"
