definitions:
  dtos.LoginProps:
    properties:
      password:
        type: string
      username:
        type: string
    required:
    - password
    - username
    type: object
  dtos.LoginResponseDTO:
    properties:
      token:
        type: string
      username:
        type: string
    type: object
info:
  contact:
    email: ceo@nrmnqdds.com
    name: Quddus
    url: http://www.swagger.io/support
  description: This is the API server for Gomaluum, an API that serves i-Ma'luum data
    for ease of developer.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Gomaluum API Server
  version: "2.0"
paths:
  /api/result:
    get:
      description: Get result from i-Ma'luum
      parameters:
      - default: Bearer <Add access token here>
        description: Insert your access token
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      tags:
      - scraper
  /api/schedule:
    get:
      description: Get schedule from i-Ma'luum
      parameters:
      - default: Bearer <Add access token here>
        description: Insert your access token
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      tags:
      - scraper
  /auth/login:
    post:
      consumes:
      - application/json
      description: Logs in the user. Save the token and use it in the Authorization
        header for future requests.
      parameters:
      - description: Login properties
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/dtos.LoginProps'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dtos.LoginResponseDTO'
      tags:
      - auth
swagger: "2.0"
