linters-settings:
  govet:
    enable:
      - fieldalignment
linters:
  disable:
    # for swagger purpose
    - staticcheck
  enable:
    # https://github.com/mgechev/revive
    - revive
    # https://pkg.go.dev/golang.org/x/tools/go/analysis/passes/fieldalignment
    - govet
