# fly.toml app configuration file generated for gomaluum-v2 on 2024-12-23T12:32:52+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'gomaluum-v2'
primary_region = 'sin'

[build]

# [http_service]
#   internal_port = 1323
#   force_https = true
#   auto_stop_machines = 'stop'
#   auto_start_machines = true
#   min_machines_running = 1
#   processes = ['app']

[[services]]
  internal_port = 1323
  protocol = "tcp"

  [[services.ports]]
    handlers = ["http"]
    port = 1323

[[services]]
  internal_port = 80
  protocol = "tcp"

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
