// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package models

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjsonFd235c7DecodeGithubComNrmnqddsGomaluumInternalModels(in *jlexer.Lexer, out *PreregScheduleRequest) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "kulliyyah":
			out.Kulliyyah = string(in.String())
		case "semester":
			out.Semester = int64(in.Int64())
		case "session":
			out.Session = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonFd235c7EncodeGithubComNrmnqddsGomaluumInternalModels(out *jwriter.Writer, in PreregScheduleRequest) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"kulliyyah\":"
		out.RawString(prefix[1:])
		out.String(string(in.Kulliyyah))
	}
	{
		const prefix string = ",\"semester\":"
		out.RawString(prefix)
		out.Int64(int64(in.Semester))
	}
	{
		const prefix string = ",\"session\":"
		out.RawString(prefix)
		out.String(string(in.Session))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v PreregScheduleRequest) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonFd235c7EncodeGithubComNrmnqddsGomaluumInternalModels(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v PreregScheduleRequest) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonFd235c7EncodeGithubComNrmnqddsGomaluumInternalModels(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *PreregScheduleRequest) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonFd235c7DecodeGithubComNrmnqddsGomaluumInternalModels(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *PreregScheduleRequest) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonFd235c7DecodeGithubComNrmnqddsGomaluumInternalModels(l, v)
}
