apiVersion: apps/v1
kind: Deployment
metadata:
  name: gomaluum-deployment
  namespace: gomaluum-k8s
  labels:
    app: gomaluum
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gomaluum
  template:
    metadata:
      labels:
        app: gomaluum
    spec:
      containers:
        - image: ghcr.io/nrmnqdds/gomaluum:latest
          name: gomaluum
          imagePullPolicy: Always
          ports:
            - containerPort: 1323
          envFrom:
            - configMapRef:
                name: gomaluum-cm
