apiVersion: v1
kind: Service
metadata:
  name: gomaluum-service
  namespace: gomaluum-k8s
  labels:
    app: gomaluum-svc
spec:
  selector:
    app: gomaluum
  ports:
    - port: 1323
      targetPort: 1323
      nodePort: 30001
  type: NodePort
